repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: "3.0.0a5"
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          ["dbt-postgres==1.7.0", "sqlfluff-templater-dbt==2.3.5"]
      - id: sqlfluff-fix
        additional_dependencies:
          ["dbt-postgres==1.7.0", "sqlfluff-templater-dbt==2.3.5"]
  - repo: https://github.com/psf/black
    rev: "24.1.1"
    hooks:
      - id: black
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "" # Use the sha or tag you want to point at
  #   hooks:
  #     - id: prettier