with source as (

    select * from {{ source('retrosheet', 'src_retrosheet__events') }}

),

renamed as (

    select
        game_id,
        away_team_id,
        inn_ct as inning,
        bat_home_id as is_home_team_batter,
        outs_ct as outs,
        balls_ct as balls,
        strikes_ct as strikes,
        pitch_seq_tx as pitch_sequence,
        away_score_ct as away_team_score,
        home_score_ct as home_team_score,
        bat_id as batter_id,
        bat_hand_cd as batter_hand,
        resp_bat_id as responsible_batter_id,
        resp_bat_hand_cd as responsible_batter_hand,
        pit_id as pitcher_id,
        pit_hand_cd as pitcher_hand,
        resp_pit_id as responsible_pitcher_id,
        resp_pit_hand_cd as responsible_pitcher_hand,
        pos2_fld_id as catcher_id,
        pos3_fld_id as first_baseman_id,
        pos4_fld_id as second_baseman_id,
        pos5_fld_id as third_baseman_id,
        pos6_fld_id as shortstop_id,
        pos7_fld_id as left_fielder_id,
        pos8_fld_id as center_fielder_id,
        pos9_fld_id as right_fielder_id,
        base1_run_id as runner_on_first_id,
        base2_run_id as runner_on_second_id,
        base3_run_id as runner_on_third_id,
        event_tx as event_text,
        leadoff_fl as is_leadoff_hitter,
        ph_fl as is_pinch_hitter,
        bat_fld_cd as batter_defensive_position,
        bat_lineup_id as lineup_position,
        event_cd as event_code,
        bat_event_fl as is_batter_event,
        ab_fl as is_at_bat,
        h_cd as hit_value,
        sh_fl as is_sacrifice_hit,
        sf_fl as is_sacrifice_fly,
        event_outs_ct as outs_on_play,
        dp_fl as is_double_play,
        tp_fl as is_triple_play,
        rbi_ct as runs_batted_in,
        wp_fl as is_wild_pitch,
        pb_fl as is_passed_ball,
        fld_cd as fielded_by,
        battedball_cd as batted_ball_type,
        bunt_fl as is_gunt,
        foul_fl as is_foul,
        battedball_loc_tx as batted_ball_location,
        err_ct as number_of_errors,
        err1_fld_cd as first_error_player_id,
        err1_cd as first_error_type,
        err2_fld_cd as second_error_player_id,
        err2_cd as second_error_type,
        err3_fld_cd as third_error_player_id,
        err3_cd as third_error_type,
        bat_dest_id as batter_destination,
        run1_dest_id as runner_on_first_destination,
        run2_dest_id as runner_on_second_destination,
        run3_dest_id as runner_on_third_destination,
        bat_play_tx as play_on_batter,
        run1_play_tx as play_on_runner_on_first,
        run2_play_tx as play_on_runner_on_second,
        run3_play_tx as play_on_runner_on_third,
        run1_sb_fl as is_stolen_base_for_runner_on_first,
        run2_sb_fl as is_stolen_base_for_runner_on_second,
        run3_sb_fl as is_stolen_base_for_runner_on_third,
        run1_cs_fl as is_caught_stealing_for_runner_on_first,
        run2_cs_fl as is_caught_stealing_for_runner_on_second,
        run3_cs_fl as is_caught_stealing_for_runner_on_third,
        run1_pk_fl as is_pickoff_for_runner_on_first,
        run2_pk_fl as is_pickoff_for_runner_on_second,
        run3_pk_fl as is_pickoff_for_runner_on_third,
        run1_resp_pit_id as runner_on_first_responsible_pitcher_id,
        run2_resp_pit_id as runner_on_second_responsible_pitcher_id,
        run3_resp_pit_id as runner_on_third_responsible_pitcher_id,
        game_new_fl as is_new_game,
        game_end_fl as is_end_of_game,
        pr_run1_fl as first_base_pinch_runner_id,
        pr_run2_fl as second_base_pinch_runner_id,
        pr_run3_fl as third_base_pinch_runner_id,
        removed_for_pr_run1_id as removed_for_first_base_pinch_runner_id,
        removed_for_pr_run2_id as removed_for_second_base_pinch_runner_id,
        removed_for_pr_run3_id as removed_for_third_base_pinch_runner_id,
        removed_for_ph_bat_id as removed_for_pinch_hitter_id,
        removed_for_ph_bat_fld_cd as removed_for_pinch_hitter_position,
        po1_fld_cd as fielder_with_first_putout,
        po2_fld_cd as fielder_with_second_putout,
        po3_fld_cd as fielder_with_third_putout,
        ass1_fld_cd as fielder_with_first_assist,
        ass2_fld_cd as fielder_with_second_assist,
        ass3_fld_cd as fielder_with_third_assist,
        ass4_fld_cd as fielder_with_fourth_assist,
        ass5_fld_cd as fielder_with_fifth_assist,
        event_id,
        home_team_id,
        bat_team_id as batting_team_id,
        fld_team_id as fielding_team_id,
        bat_last_id as is_team_that_bats_last,
        inn_new_fl as is_start_of_half_inning,
        inn_end_fl as is_end_of_half_inning,
        start_bat_score_ct as score_for_batting_team,
        start_fld_score_ct as score_for_fielding_team,
        inn_runs_ct as runs_scored_in_half_inning,
        game_pa_ct as batting_team_plate_appearances_in_game,
        inn_pa_ct as batting_team_plate_appearances_in_inning,
        pa_new_fl as start_of_plate_appearance,
        pa_trunc_fl as truncated_plate_appearance,
        start_bases_cd as start_of_play_base_state,
        end_bases_cd as end_of_play_base_state,
        bat_start_fl as is_batter_starter,
        resp_bat_start_fl as is_responsible_batter_starter,
        bat_on_deck_id as on_deck_batter_id,
        bat_in_hold_id as in_the_hole_batter_id,
        pit_start_fl as is_pitcher_starter,
        resp_pit_start_fl as is_responsible_pitcher_starter,
        run1_fld_cd as runner_on_first_defensive_position,
        run1_lineup_cd as runner_on_first_lineup_position,
        run1_origin_event_id as runner_on_first_origin_event_id,
        run2_fld_cd as runner_on_second_defensive_position,
        run2_lineup_cd as runner_on_second_lineup_position,
        run2_origin_event_id as runner_on_second_origin_event_id,
        run3_fld_cd as runner_on_third_defensive_position,
        run3_lineup_cd as runner_on_third_lineup_position,
        run3_origin_event_id as runner_on_third_origin_event_id,
        run1_resp_cat_id as runner_on_first_repsonsible_catcher_id,
        run2_resp_cat_id as runner_on_second_responsible_cathcer_id,
        run3_resp_cat_id as runner_on_third_responsible_catcher_id,
        pa_ball_ct as balls_in_plate_appearance,
        pa_called_ball_ct as called_balls_in_plate_appearance,
        pa_intent_ball_ct as intentional_balls_in_plate_appearance,
        pa_pitchout_ball_ct as pitchouts_in_plate_appearance,
        pa_hitbatter_ball_ct as pitches_hitting_batter_in_plate_appearance,
        pa_other_ball_ct as other_balls_in_plate_appearance,
        pa_strike_ct as strikes_in_plate_appearance,
        pa_called_strike_ct as called_strikes_in_plate_appearance,
        pa_swingmiss_strike_ct as swinging_strikes_in_plate_appearance,
        pa_foul_strike_ct as foul_balls_in_plate_appearance,
        pa_inplay_strike_ct as balls_in_play_in_plate_appearance,
        pa_other_strike_ct as other_strikes_in_plate_appearance,
        event_runs_ct as runs_on_play,
        fld_id as fielder_playing_batted_ball_id,
        base2_force_fl as is_force_play_at_second,
        base3_force_fl as is_force_play_at_third,
        base4_force_fl as is_force_play_at_home,
        bat_safe_err_fl as is_batter_safe_on_error,
        bat_fate_id as fate_of_batter,
        run1_fate_id as fate_of_runner_on_first,
        run2_fate_id as fate_of_runner_on_second,
        run3_fate_id as fate_of_runner_on_third,
        fate_runs_ct as runs_scored_in_half_inning_after_event,
        ass6_fld_cd as fielder_with_sixth_assist,
        ass7_fld_cd as fielder_with_seventh_assist,
        ass8_fld_cd as fielder_with_eighth_assist,
        ass9_fld_cd as fielder_with_ninth_assist,
        ass10_fld_cd as fielder_with_tenth_assist,
        loaded_at,
        md5(
            coalesce(game_id, '') || coalesce(event_id::varchar, '')
        ) as game_event_hash_id

    from source

)

select * from renamed
